/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package subInterfaz;

import java.awt.GridLayout;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;
import util.ActualizarTiempo;

/**
 *
 * @author danyc
 */
public class ImprimirTicket extends javax.swing.JFrame {

    private static int filas;
    private DefaultTableModel dtm;

    public ImprimirTicket(int filas) {
        initComponents();
        lbEmpleado.setText(GenerarCorteCaja.lbUser.getText());
        dtm = GenerarCorteCaja.m;
        this.filas = dtm.getRowCount()+3;
        Date date = new Date();
              
        DateFormat hourFormat = new SimpleDateFormat("HH:mm:ss");
        lbHora.setText(hourFormat.format(date));
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        lbFecha.setText(dateFormat.format(date));

        panelLabes.setLayout(new GridLayout(this.filas, 3));
        jPanel1.setBounds(0, 0, 300, (175 + (this.filas * 50)));
        System.out.println(panelLabes.getX() + "-" + panelLabes.getY());
        panelLabes.setBounds(panelLabes.getX(), panelLabes.getY(), 300, 50 * this.filas);

        for (int i = 0; i < this.filas-3; i++) {
            JLabel label = new JLabel();
            label.setFont(new java.awt.Font("Segoe UI", 0, 14));
            label.setBackground(new java.awt.Color(255, 255, 255));
            label.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
            label.setText(dtm.getValueAt(i, 0).toString());
            panelLabes.add(label);
            JLabel label2 = new JLabel();
            label2.setFont(new java.awt.Font("Segoe UI", 0, 14));
            if(label.getText().equals("Gasto"))
                label2.setText("-"+dtm.getValueAt(i, 2).toString());
            else
                label2.setText("+"+dtm.getValueAt(i, 2).toString());
            label2.setBackground(new java.awt.Color(255, 255, 255));
            label2.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
            panelLabes.add(label2);
            JLabel label3 = new JLabel();
            label3.setFont(new java.awt.Font("Segoe UI", 0, 14));
            label3.setBackground(new java.awt.Color(255, 255, 255));
            label3.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
            label3.setText(dtm.getValueAt(i, 3).toString());
            panelLabes.add(label3);
            
          System.out.println(label3.getX() + "-" + label3.getY());
        }
        for (int i = 0; i < 3; i++) {
            JLabel lb = new JLabel("");
            panelLabes.add(lb);
        }
        JLabel labels[] = new JLabel[6];
        String titulos[] = {"Contado","Calculado","Diferencia"};
        for (int i = 0; i < 3; i++) {
            labels[i] = new JLabel();
            labels[i].setFont(new java.awt.Font("Segoe UI", 0, 14));
            labels[i].setBackground(new java.awt.Color(255, 255, 255));
            labels[i].setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
            labels[i].setText(titulos[i]);
            panelLabes.add(labels[i]);
        }
        String numeros[] = {GenerarCorteCaja.lbDinero.getText(),GenerarCorteCaja.lbCalculado.getText(),GenerarCorteCaja.lbDiferencia.getText()};
        for (int i = 3; i < 6; i++) {
            labels[i] = new JLabel();
            labels[i].setFont(new java.awt.Font("Segoe UI", 1, 14));
            labels[i].setBackground(new java.awt.Color(255, 255, 255));
            labels[i].setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
            labels[i].setText(numeros[i-3]);
            panelLabes.add(labels[i]);
        }

        this.setBounds(0, 0, 300, (175 + (this.filas * 50)));
//        JLabel label4 = new JLabel("nuev0");
//        label4.setBounds(50, (175 + (this.filas * 50)+50), 70, (175 + (this.filas * 50)+70));
//        jPanel1.add(label4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbFecha = new javax.swing.JLabel();
        lbHora = new javax.swing.JLabel();
        panelLabes = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbEmpleado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 300));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 300));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pizza Manager");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Corte de caja");

        lbFecha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbFecha.setText("31/05/2021");

        lbHora.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbHora.setText("18:58:45");
        lbHora.setToolTipText("");

        panelLabes.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelLabesLayout = new javax.swing.GroupLayout(panelLabes);
        panelLabes.setLayout(panelLabesLayout);
        panelLabesLayout.setHorizontalGroup(
            panelLabesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 287, Short.MAX_VALUE)
        );
        panelLabesLayout.setVerticalGroup(
            panelLabesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 166, Short.MAX_VALUE)
        );

        jLabel3.setText("Fecha");

        jLabel4.setText("Hora");

        jLabel5.setText("Tipo");

        jLabel6.setText("Importe");

        jLabel7.setText("Hora");

        jLabel8.setText("Empleado");

        lbEmpleado.setText("empleado");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelLabes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(lbEmpleado)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(53, 53, 53)
                        .addComponent(jLabel6)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(lbHora, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(95, 95, 95))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lbEmpleado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbFecha)
                    .addComponent(lbHora)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelLabes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImprimirTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImprimirTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImprimirTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImprimirTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImprimirTicket(filas).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbEmpleado;
    private javax.swing.JLabel lbFecha;
    private javax.swing.JLabel lbHora;
    private javax.swing.JPanel panelLabes;
    // End of variables declaration//GEN-END:variables
}
