/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import java.awt.Toolkit;

/**
 *
 * @author danyc
 */
public class FormAperturaCaja extends javax.swing.JFrame {

    public static FormAperturaCaja obj;
    
    public static FormAperturaCaja getObj(){
        if(obj==null){
            obj=new FormAperturaCaja();
        }return obj;
    }
    
    
    public FormAperturaCaja() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("../Images/icon.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        billeteMil = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cantidad = new javax.swing.JLabel();
        btnAperturar = new javax.swing.JButton();
        mas1000 = new javax.swing.JButton();
        menos1000 = new javax.swing.JButton();
        menos500 = new javax.swing.JButton();
        billeteQui = new javax.swing.JTextField();
        mas500 = new javax.swing.JButton();
        menos200 = new javax.swing.JButton();
        mas200 = new javax.swing.JButton();
        billeteDoscientos = new javax.swing.JTextField();
        menos100 = new javax.swing.JButton();
        mas100 = new javax.swing.JButton();
        billeteCien = new javax.swing.JTextField();
        menos50 = new javax.swing.JButton();
        mas50 = new javax.swing.JButton();
        billeteCincuenta = new javax.swing.JTextField();
        menos20b = new javax.swing.JButton();
        mas20b = new javax.swing.JButton();
        billeteVeinteB = new javax.swing.JTextField();
        mas20 = new javax.swing.JButton();
        monedaVeinteM = new javax.swing.JTextField();
        menos20 = new javax.swing.JButton();
        menos10 = new javax.swing.JButton();
        monedaDiez = new javax.swing.JTextField();
        mas10 = new javax.swing.JButton();
        mas5 = new javax.swing.JButton();
        monedaCinco = new javax.swing.JTextField();
        menos5 = new javax.swing.JButton();
        menos2 = new javax.swing.JButton();
        monedaDos = new javax.swing.JTextField();
        mas2 = new javax.swing.JButton();
        mas1 = new javax.swing.JButton();
        monedaPeso = new javax.swing.JTextField();
        menos1 = new javax.swing.JButton();
        menos050 = new javax.swing.JButton();
        monedaCincuentaCent = new javax.swing.JTextField();
        mas050 = new javax.swing.JButton();
        btnCalcular = new javax.swing.JButton();

        jLabel3.setText("jLabel3");

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Apertura de Caja");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Apertura de Caja");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 80));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 204));

        btnCancelar.setBackground(new java.awt.Color(255, 51, 51));
        btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 0, 51));
        btnCancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCancelar.setText("Cancelar");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("$200");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Billetes");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("$500");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("$100");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("$50");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("$20");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("$1000");

        billeteMil.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        billeteMil.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        billeteMil.setText("0");
        billeteMil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billeteMilActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("Monedas");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("$20");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("$10");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("$5");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("$2");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("$1");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("$0.50");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Cantidad");

        cantidad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cantidad.setText("$------");

        btnAperturar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAperturar.setText("Aperturar");
        btnAperturar.setEnabled(false);

        mas1000.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mas1000.setText("+");
        mas1000.setBorder(null);
        mas1000.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mas1000.setOpaque(true);

        menos1000.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menos1000.setText("-");
        menos1000.setToolTipText("");
        menos1000.setBorder(null);
        menos1000.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menos1000.setOpaque(true);

        menos500.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menos500.setText("-");
        menos500.setBorder(null);
        menos500.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menos500.setOpaque(true);

        billeteQui.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        billeteQui.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        billeteQui.setText("0");
        billeteQui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billeteQuiActionPerformed(evt);
            }
        });

        mas500.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mas500.setText("+");
        mas500.setBorder(null);
        mas500.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mas500.setOpaque(true);

        menos200.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menos200.setText("-");
        menos200.setBorder(null);
        menos200.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menos200.setOpaque(true);

        mas200.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mas200.setText("+");
        mas200.setBorder(null);
        mas200.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mas200.setOpaque(true);

        billeteDoscientos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        billeteDoscientos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        billeteDoscientos.setText("0");
        billeteDoscientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billeteDoscientosActionPerformed(evt);
            }
        });

        menos100.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menos100.setText("-");
        menos100.setBorder(null);
        menos100.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menos100.setOpaque(true);

        mas100.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mas100.setText("+");
        mas100.setBorder(null);
        mas100.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mas100.setOpaque(true);

        billeteCien.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        billeteCien.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        billeteCien.setText("0");
        billeteCien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billeteCienActionPerformed(evt);
            }
        });

        menos50.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menos50.setText("-");
        menos50.setBorder(null);
        menos50.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menos50.setOpaque(true);

        mas50.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mas50.setText("+");
        mas50.setBorder(null);
        mas50.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mas50.setOpaque(true);

        billeteCincuenta.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        billeteCincuenta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        billeteCincuenta.setText("0");
        billeteCincuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billeteCincuentaActionPerformed(evt);
            }
        });

        menos20b.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menos20b.setText("-");
        menos20b.setBorder(null);
        menos20b.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menos20b.setOpaque(true);

        mas20b.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mas20b.setText("+");
        mas20b.setBorder(null);
        mas20b.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mas20b.setOpaque(true);

        billeteVeinteB.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        billeteVeinteB.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        billeteVeinteB.setText("0");
        billeteVeinteB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billeteVeinteBActionPerformed(evt);
            }
        });

        mas20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mas20.setText("+");
        mas20.setBorder(null);
        mas20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mas20.setOpaque(true);

        monedaVeinteM.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        monedaVeinteM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        monedaVeinteM.setText("0");
        monedaVeinteM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monedaVeinteMActionPerformed(evt);
            }
        });

        menos20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menos20.setText("-");
        menos20.setBorder(null);
        menos20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menos20.setOpaque(true);

        menos10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menos10.setText("-");
        menos10.setBorder(null);
        menos10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menos10.setOpaque(true);

        monedaDiez.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        monedaDiez.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        monedaDiez.setText("0");
        monedaDiez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monedaDiezActionPerformed(evt);
            }
        });

        mas10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mas10.setText("+");
        mas10.setBorder(null);
        mas10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mas10.setOpaque(true);

        mas5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mas5.setText("+");
        mas5.setBorder(null);
        mas5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mas5.setOpaque(true);

        monedaCinco.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        monedaCinco.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        monedaCinco.setText("0");
        monedaCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monedaCincoActionPerformed(evt);
            }
        });

        menos5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menos5.setText("-");
        menos5.setBorder(null);
        menos5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menos5.setOpaque(true);

        menos2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menos2.setText("-");
        menos2.setBorder(null);
        menos2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menos2.setOpaque(true);

        monedaDos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        monedaDos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        monedaDos.setText("0");
        monedaDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monedaDosActionPerformed(evt);
            }
        });

        mas2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mas2.setText("+");
        mas2.setBorder(null);
        mas2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mas2.setOpaque(true);

        mas1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mas1.setText("+");
        mas1.setBorder(null);
        mas1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mas1.setOpaque(true);

        monedaPeso.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        monedaPeso.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        monedaPeso.setText("0");
        monedaPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monedaPesoActionPerformed(evt);
            }
        });

        menos1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menos1.setText("-");
        menos1.setBorder(null);
        menos1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menos1.setOpaque(true);

        menos050.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menos050.setText("-");
        menos050.setBorder(null);
        menos050.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menos050.setOpaque(true);
        menos050.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menos050ActionPerformed(evt);
            }
        });

        monedaCincuentaCent.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        monedaCincuentaCent.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        monedaCincuentaCent.setText("0");
        monedaCincuentaCent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monedaCincuentaCentActionPerformed(evt);
            }
        });

        mas050.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mas050.setText("+");
        mas050.setBorder(null);
        mas050.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mas050.setOpaque(true);

        btnCalcular.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCalcular.setText("Calcular");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(menos1000, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(billeteMil, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(mas1000, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addComponent(menos500, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(billeteQui, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(mas500, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                        .addComponent(menos200, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(billeteDoscientos, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(mas200, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                    .addComponent(menos100, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(billeteCien, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(mas100, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(menos50, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(billeteCincuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(mas50, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                            .addComponent(menos20b, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(billeteVeinteB, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(mas20b, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 28, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(menos20, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(monedaVeinteM, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(mas20, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(menos2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(monedaDos, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(mas2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addComponent(menos1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(monedaPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(mas1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addComponent(menos5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(monedaCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(mas5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(menos10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(monedaDiez, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(mas10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(menos050, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(monedaCincuentaCent, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(mas050, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(13, 13, 13))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(btnAperturar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(90, 90, 90))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(billeteMil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mas1000)
                            .addComponent(menos1000)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(billeteQui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mas500)
                            .addComponent(menos500))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(billeteDoscientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mas200)
                            .addComponent(menos200))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(billeteCien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mas100)
                            .addComponent(menos100)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(monedaVeinteM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mas20)
                            .addComponent(menos20)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(menos10)
                            .addComponent(monedaDiez, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mas10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(monedaCinco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mas5)
                            .addComponent(menos5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(monedaDos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mas2)
                            .addComponent(menos2))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(monedaPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mas1)
                            .addComponent(menos1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(monedaCincuentaCent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mas050)
                            .addComponent(menos050)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(billeteCincuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mas50)
                            .addComponent(menos50)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(billeteVeinteB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(mas20b)
                                .addComponent(menos20b)))))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cantidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAperturar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 590, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void monedaCincuentaCentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monedaCincuentaCentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monedaCincuentaCentActionPerformed

    private void menos050ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menos050ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menos050ActionPerformed

    private void monedaPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monedaPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monedaPesoActionPerformed

    private void monedaDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monedaDosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monedaDosActionPerformed

    private void monedaCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monedaCincoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monedaCincoActionPerformed

    private void monedaDiezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monedaDiezActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monedaDiezActionPerformed

    private void monedaVeinteMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monedaVeinteMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monedaVeinteMActionPerformed

    private void billeteVeinteBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billeteVeinteBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_billeteVeinteBActionPerformed

    private void billeteCincuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billeteCincuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_billeteCincuentaActionPerformed

    private void billeteCienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billeteCienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_billeteCienActionPerformed

    private void billeteDoscientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billeteDoscientosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_billeteDoscientosActionPerformed

    private void billeteQuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billeteQuiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_billeteQuiActionPerformed

    private void billeteMilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billeteMilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_billeteMilActionPerformed

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        this.dispose();

    }//GEN-LAST:event_btnCancelarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAperturaCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAperturaCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAperturaCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAperturaCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAperturaCaja().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField billeteCien;
    public javax.swing.JTextField billeteCincuenta;
    public javax.swing.JTextField billeteDoscientos;
    public javax.swing.JTextField billeteMil;
    public javax.swing.JTextField billeteQui;
    public javax.swing.JTextField billeteVeinteB;
    public javax.swing.JButton btnAperturar;
    public javax.swing.JButton btnCalcular;
    public javax.swing.JLabel btnCancelar;
    public javax.swing.JLabel cantidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    public javax.swing.JButton mas050;
    public javax.swing.JButton mas1;
    public javax.swing.JButton mas10;
    public javax.swing.JButton mas100;
    public javax.swing.JButton mas1000;
    public javax.swing.JButton mas2;
    public javax.swing.JButton mas20;
    public javax.swing.JButton mas200;
    public javax.swing.JButton mas20b;
    public javax.swing.JButton mas5;
    public javax.swing.JButton mas50;
    public javax.swing.JButton mas500;
    public javax.swing.JButton menos050;
    public javax.swing.JButton menos1;
    public javax.swing.JButton menos10;
    public javax.swing.JButton menos100;
    public javax.swing.JButton menos1000;
    public javax.swing.JButton menos2;
    public javax.swing.JButton menos20;
    public javax.swing.JButton menos200;
    public javax.swing.JButton menos20b;
    public javax.swing.JButton menos5;
    public javax.swing.JButton menos50;
    public javax.swing.JButton menos500;
    public javax.swing.JTextField monedaCinco;
    public javax.swing.JTextField monedaCincuentaCent;
    public javax.swing.JTextField monedaDiez;
    public javax.swing.JTextField monedaDos;
    public javax.swing.JTextField monedaPeso;
    public javax.swing.JTextField monedaVeinteM;
    // End of variables declaration//GEN-END:variables
}
